[workspace]
members = [
    "plonkish-encoding",
    "plonkish-relation",
]
resolver = "2"

[workspace.package]
version = "0.0.0"
authors = [
    "Jack Grigg <thestr4d@gmail.com>",
]
edition = "2021"
license = "MIT OR Apache-2.0"
