[package]
name = "plonkish-encoding"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "An encoding format for PLONKish arithmetic circuits"
license.workspace = true

[dependencies]
