[package]
name = "plonkish-relation"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Specification of the PLONKish relation in hacspec"
license.workspace = true

[dependencies]
