name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
      - run: cargo fetch
      - name: Build tests
        run: cargo build --workspace --verbose --all-features --tests
      - name: Run tests
        run: cargo test --workspace --verbose --all-features
